name: AI Code Review

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize ]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Code Review
        uses: anc95/ChatGPT-CodeReview@main
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: gpt-4
          LANGUAGE: en
          TOP_P: 1
          TEMPERATURE: 1
          MAX_TOKENS: 10000

  # Notes:
  # - This workflow is optional and will not block PRs if it fails
  # - If OPENAI_API_KEY is not configured, the step will fail but continue
  # - Add OPENAI_API_KEY secret to enable AI reviews
  #
  # Alternative: Use CodeRabbit for free AI reviews
  # 1. Visit https://coderabbit.ai/
  # 2. Install the CodeRabbit GitHub App to your repository
  # 3. Disable this workflow (delete file or comment out job)
  # 4. CodeRabbit will automatically review all PRs with AI assistance
