name: AI Code Review

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize ]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          model: gpt-4
          review_comment_lgtm: false
          language: en
          top_p: 1
          temperature: 1
          max_tokens: 10000
          review_simple_changes: false

  # Alternative: Use CodeRabbit for free AI reviews
  # To enable CodeRabbit:
  # 1. Visit https://coderabbit.ai/
  # 2. Install the CodeRabbit GitHub App to your repository
  # 3. Comment out or remove the ai-review job above
  # CodeRabbit will automatically review all PRs with AI assistance
